name: henbot_stack
root: ~/Bird_Up/workspace

startup_window: main

attach: false

windows:
  - core:
      - roscore
  - main:
      layout: tiled
      pre: sleep 5
      panes:
      - rosrun jetbot_ros jetbot_camera
      - rosrun vision camera.py

        

